branch-defaults:
  default:
    environment: test-env
    group_suffix: null
global:
  application_name: test-app
  branch: null
  default_ec2_keyname: test-app-key-pair
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
